# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='NULL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='NULL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('userLevel', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='messageAuthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userMessage', to='dashboardApp.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commentAuthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userComment', to='dashboardApp.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commentsMessage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageComment', to='dashboardApp.Message'),
        ),
    ]
