# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default='Default Description'),
        ),
    ]
